name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false

jobs:
  mirrorchyan:
    if: ${{ github.repository_owner == 'Maa-Assistant-PVZ-The-best' }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        os: [win, macos, linux]
        arch: [aarch64, x86_64]
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ format('MaaPVZ-{0}-{1}-*', matrix.os, matrix.arch) }}
          mirrorchyan_rid: MaaPVZ
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: Maa-Assistant-PVZ-The-best
          repo: MAAPVZ
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
